### ISSUE TITLE
Various Remarks

### ISSUE THREAD

**Issue by jens-diewald** [laudrup/boost-wintls#56]
Hi!
First of all, thanks for putting together this very useful library.
I have been using beast+asio(and hence openssl)+[djarek/certify](https://github.com/djarek/certify) for a simple https client so far.
But i do prefer your approach and would like to replace openssl+certify by your library.
Here are a few notes from first tests:

1. Server hostnames are not verified during certificate validation. (Testcase: wrong.host.badssl.com:443)
 This should be a relatively easy fix if i am not missing something. I can add a small pull request later for further details.
2. There are several more (probably less important) test cases on badssl.com, that are not handled as the site suggests they should be.
 Checking a revocation list should be relatively straight forward, not sure about the other cases.
3. Trying to connect to client.badssl.com:443 yields a failed assert due to client certificates not being implemented. I think it would be nicer to throw an exception in such a case, so the caller can recover from the error. (Since there is #55 now, this particular case is probably not a problem for long though :) )
4. I needed to link against secur32.lib and crypt32.lib to use the library (You have listed even two more in your cmake config). This should be documented somewhere. Maybe we can even have some pragma comment lib for convenience?
5. I am not sure how far you are aiming for compability with asio/ssl, but i ran into a few differences. This is no big issue for me, but a higher compatibility would be nice to allow simple cross platform code to use wintls on windows and asio with openssl on unix systems.
   - wintls has context::use_default_certificates(bool) instead of context::set_default_verify_paths(). I think use_default_certificates is the better (more general) name and i suppose windows does not really have "verify paths". But maybe the other function could be introduced as an alias for compability?
   - wintls has context::verify_server_certificate(bool) instead of context::set_verify_mode(verify_mode). Here the latter is more general, but as i understand it wintls does not (yet) have all the functionality that asio provides here. It would be nice to somewhat align this with asio in the future. (As also mentioned here: https://github.com/laudrup/boost-wintls/issues/53#issuecomment-1169608161)
   - wintls uses some scoped enums (wintls::method, wintls::handshake_type) which are different from the asio equivalents. I generally like the wintls way much better, not sure what could be done here...
   - There is no wintls::error::stream_truncated. The asio equivalent is a common error that i have to handle. (Not sure what wintls yields in these cases yet.)
   - Many wintls classes have their move constructors explicitly deleted. Is there a good reason for that? At first glance, your usage of unique_ptr should prevent any problems with moves? (Why i noticed: In my original code i had a separate function to initialize the ssl::context, set some parameters as verify_mode, etc. and return it. I had to solve this differently to work with wintls.)

**Comment by laudrup** [comment]
@jens-diewald 

I assume we can close this now?

**Comment by jens-diewald** [comment]
Hi, there are a few small points in here that are still relevant i think:
* Deleted move constructors - i just looked into this a bit and found, that `context` and `stream` should indeed be movable without problems. (Actually the move constructor for stream is defaulted, while the move assignment is deleted, i suppose this is not intended?)
-> I will add two small pull requests to remove the deleting of move operations for these two classes.
* An example how to use `wintls` alongside `asio.ssl` as you proposed above would be helpful. I can see if i can add a variant of the https_client example based on my code.
* I did not get to testing regarding `asio::ssl::error::stream_truncated`. The error is described as `The underlying stream closed before the ssl stream gracefully shut down.`. This seems to happen in many cases as closing an ssl connection properly is relatively complicated. Maybe there is nothing to do here, but at least for the use case of using `wintls` alongside `asio.ssl` it would be nice to know what `wintls` does in such cases.

**Comment by laudrup** [comment]
@jens-diewald 

* i've merged your PRs that introduced the move cosntructors. Thanks for that. A small but relevant improvement.

* It would be nice to add an example of how to use `wintls` alongside `asio.ssl`. A PR for this would be much appreciated.

* I haven't really looked into the details of shutting down the stream correctly although I know there are some tests for that. Maybe those tests could be extended to document what happens?

**Comment by jens-diewald** [comment]
I have opened #75 for the stream_truncated issue.
I have also done some work on a simple syncronous https client example to show the usage of WinTLS beside Asio.SSL. I am not super happy with it, but i may add a PR for this soon.
Anyhow, i think this can be closed now :)
