### ISSUE TITLE
TLS v1.3 not work

### ISSUE THREAD

**Issue by windowsair** [laudrup/boost-wintls#83]
It looks like TLS v1.3 is not working properly, as shown in the unit test.

I think we should change the API we used, as shown in the following reference link:
https://github.com/curl/curl/pull/7784

Unfortunately, it doesn't appear that MS has documented this.

**Comment by laudrup** [comment]
Hi @windowsair 

Sorry for the very late reply.

It seems like you are right that this does not work when building on Windows 2022 where TLS 1.3 ought to be supported.

I am not sure what might be the cause of this but I am afraid I'm not really able to look into this as I don't currently have access to any build machine running Windows 2022 (or Windows 11) which seems to be required to use TLS 1.3 with SChannel.

Implementing by pushing and getting output from GitHub actions is not really worth it, so unless I get access to a Windows 11 installation somehow I don't think I can fix this right now.

Any pull requests related to this would be very much appreciated.
